"""Platform-specific bridge installer script templates.

Each template is rendered server-side with the agent's freshly-regenerated
API key and the resolved WebSocket server URL baked in, then returned as
an attachment for the user to run locally.

Windows: returns a single `clawith-bridge-setup.exe` — the pristine
PyInstaller binary with a config trailer (JSON + magic) appended at EOF.
The user double-clicks it; the bridge detects the trailer on startup,
runs the install flow, strips the trailer from the installed copy at
%LOCALAPPDATA%\\Clawith\\bin\\, and registers a scheduled task. No ZIP,
no manual extraction, no install.cmd.

macOS/Linux: returns a bash script that pip-installs `clawith-bridge`
and registers launchd/systemd user services.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

Platform = Literal["windows", "macos", "linux"]

# Wire format shared with `bridge/clawith_bridge/baked_config.py`. If you
# change either side, change the other. Structure at end of file:
#   [json utf-8 blob] [4B pristine_len BE] [8B magic]
_TRAILER_MAGIC: bytes = b"CLWB!END"
_TRAILER_LEN_BYTES = 4


# Location of the bundled bridge exe. Kept inside the backend package so
# it ships via the normal Dockerfile `COPY . .` step.
_BRIDGE_EXE_PATH = (
    Path(__file__).resolve().parent.parent.parent / "static" / "bridge" / "clawith-bridge.exe"
)


_UNIX_SH = r"""#!/usr/bin/env bash
# Clawith Bridge Installer (auto-generated)
# Agent: {agent_name}
# Run:  bash install-clawith-bridge.sh

set -euo pipefail

CLAWITH_SERVER="{server_url}"
CLAWITH_TOKEN="{api_key}"

echo "[clawith-bridge] Checking Python..."
if ! command -v python3 >/dev/null 2>&1; then
    echo "[clawith-bridge] ERROR: python3 not found. Install Python 3.10+ first." >&2
    exit 1
fi

# Check if clawith-bridge is already installed (dev mode or prior install).
if python3 -c "import clawith_bridge" 2>/dev/null; then
    echo "[clawith-bridge] Package already installed - skipping pip install"
else
    echo "[clawith-bridge] Installing clawith-bridge via pip..."
    if ! python3 -m pip install --user --upgrade clawith-bridge; then
        # pip failed (e.g. package not on PyPI yet). Re-check import; if still missing, abort.
        if ! python3 -c "import clawith_bridge" 2>/dev/null; then
            echo "[clawith-bridge] ERROR: pip install failed and clawith_bridge is not importable." >&2
            echo "   If you are testing from a local repo, install it first:" >&2
            echo "     python3 -m pip install -e <path-to-clawith>/bridge" >&2
            exit 1
        fi
    fi
fi

CONFIG_PATH="$HOME/.clawith-bridge.toml"
echo "[clawith-bridge] Writing config to $CONFIG_PATH"
cat > "$CONFIG_PATH" <<EOF
# Auto-generated by Clawith installer. Do not share this file - it contains your API key.
server = "$CLAWITH_SERVER"
token  = "$CLAWITH_TOKEN"

max_concurrent_sessions = 4

[claude_code]
enabled    = {cc_enabled}
executable = "claude"

[hermes]
enabled  = {hm_enabled}
base_url = "http://127.0.0.1:7890"

[openclaw]
enabled  = {oc_enabled}
base_url = "http://127.0.0.1:9000"
EOF
chmod 600 "$CONFIG_PATH"

UNAME="$(uname -s)"
if [[ "$UNAME" == "Darwin" ]]; then
    # ── macOS: launchctl user agent ─────────────────────
    PLIST_DIR="$HOME/Library/LaunchAgents"
    PLIST="$PLIST_DIR/com.clawith.bridge.plist"
    mkdir -p "$PLIST_DIR"
    cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.clawith.bridge</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/env</string>
        <string>python3</string>
        <string>-m</string>
        <string>clawith_bridge</string>
    </array>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>$HOME/Library/Logs/clawith-bridge.log</string>
    <key>StandardErrorPath</key><string>$HOME/Library/Logs/clawith-bridge.err.log</string>
</dict>
</plist>
EOF
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load "$PLIST"
    echo ""
    echo "[clawith-bridge] Done."
    echo "   Config: $CONFIG_PATH"
    echo "   Agent:  com.clawith.bridge (launchd, auto-starts at login)"
    echo "   Logs:   tail -f ~/Library/Logs/clawith-bridge.log"
elif [[ "$UNAME" == "Linux" ]]; then
    # ── Linux: systemd --user ───────────────────────────
    UNIT_DIR="$HOME/.config/systemd/user"
    mkdir -p "$UNIT_DIR"
    cat > "$UNIT_DIR/clawith-bridge.service" <<EOF
[Unit]
Description=Clawith Bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%h/.local/bin/clawith-bridge
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    systemctl --user daemon-reload
    systemctl --user enable --now clawith-bridge.service
    echo ""
    echo "[clawith-bridge] Done."
    echo "   Config:   $CONFIG_PATH"
    echo "   Service:  clawith-bridge.service (systemd --user)"
    echo "   Status:   systemctl --user status clawith-bridge"
    echo "   Logs:     journalctl --user -u clawith-bridge -f"

    # systemd user service only runs while user session is active by default.
    # Enable lingering so it keeps running after logout (optional).
    if ! loginctl show-user "$USER" 2>/dev/null | grep -q "Linger=yes"; then
        echo ""
        echo "   Tip: enable linger so the service runs even when you're not logged in:"
        echo "     sudo loginctl enable-linger $USER"
    fi
else
    echo "[clawith-bridge] Unknown platform: $UNAME — config written, but autostart not configured." >&2
    echo "   Run manually:  clawith-bridge" >&2
fi

echo ""
echo "   If Clawith still shows 'Bridge not connected', ensure 'claude' CLI is installed and logged in:"
echo "     npm install -g @anthropic-ai/claude-code"
echo "     claude login"
"""


_KNOWN_ADAPTERS = ("claude_code", "openclaw", "hermes")


def _adapter_enabled_flags(adapter: str) -> dict[str, str]:
    """Return `{"cc_enabled": ..., "hm_enabled": ..., "oc_enabled": ...}` —
    three TOML bool literals with only `adapter` set to `true`. Unknown
    adapters default to claude_code."""
    if adapter not in _KNOWN_ADAPTERS:
        adapter = "claude_code"
    return {
        "cc_enabled": "true" if adapter == "claude_code" else "false",
        "hm_enabled": "true" if adapter == "hermes" else "false",
        "oc_enabled": "true" if adapter == "openclaw" else "false",
    }


def render_installer(
    platform: Platform,
    *,
    server_url: str,
    api_key: str,
    agent_name: str,
    adapter: str = "claude_code",
) -> tuple[bytes, str, str]:
    """Render a platform-specific installer.

    `adapter` picks which bridge adapter the generated TOML (or baked
    trailer, on Windows) enables — one of 'claude_code' | 'openclaw' |
    'hermes'.

    Returns (payload_bytes, filename, content_type).
    For Windows, payload is a single self-configuring .exe; for Unix, a
    bash script.
    """
    # Safety: template is a trusted constant, and we only format with values that
    # come from server-controlled sources (agent name, generated token, derived URL).
    # `agent_name` is the only user-controlled string that lands in a comment line.
    safe_name = agent_name.replace("\n", " ").replace("\r", " ")[:200]

    if platform == "windows":
        payload = _render_windows_exe(
            server_url=server_url,
            api_key=api_key,
            agent_name=safe_name,
            adapter=adapter,
        )
        return (
            payload,
            "clawith-bridge-setup.exe",
            "application/vnd.microsoft.portable-executable",
        )

    text = _UNIX_SH.format(
        agent_name=safe_name,
        server_url=server_url,
        api_key=api_key,
        **_adapter_enabled_flags(adapter),
    )
    return (
        text.encode("utf-8"),
        "install-clawith-bridge.sh",
        "text/x-shellscript; charset=utf-8",
    )


def _render_windows_exe(*, server_url: str, api_key: str, agent_name: str, adapter: str) -> bytes:
    """Return pristine bridge exe bytes + baked-config trailer at EOF.

    The trailer encodes the server URL, agent token, agent name, and chosen
    adapter as JSON. Bridge startup reads it via
    `baked_config.read_baked_config()` and runs the install flow
    automatically on first double-click.
    """
    if not _BRIDGE_EXE_PATH.exists():
        raise FileNotFoundError(
            f"bundled clawith-bridge.exe is missing at {_BRIDGE_EXE_PATH}. "
            "Build it via: cd bridge/ && pyinstaller clawith-bridge.spec --clean, "
            "then copy dist/clawith-bridge.exe to backend/app/static/bridge/."
        )

    pristine = _BRIDGE_EXE_PATH.read_bytes()
    config = {
        "server": server_url,
        "token": api_key,
        "agent_name": agent_name,
        "adapter": adapter if adapter in _KNOWN_ADAPTERS else "claude_code",
    }
    blob = json.dumps(config, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    pristine_len = len(pristine)
    trailer = blob + pristine_len.to_bytes(_TRAILER_LEN_BYTES, "big") + _TRAILER_MAGIC
    return pristine + trailer


def derive_ws_url(http_base: str) -> str:
    """Convert an HTTP(S) base URL to its WebSocket equivalent.

    `http://host:port`  -> `ws://host:port`
    `https://host:port` -> `wss://host:port`
    """
    if http_base.startswith("https://"):
        return "wss://" + http_base[len("https://"):]
    if http_base.startswith("http://"):
        return "ws://" + http_base[len("http://"):]
    # Already ws(s)?:// — return as-is
    return http_base
