"""One-shot Windows installer.

Copies the running frozen .exe to %LOCALAPPDATA%\\Clawith\\bin\\, writes
~/.clawith-bridge.toml (UTF-8 no BOM), and registers a user-scope scheduled
task that auto-starts the bridge at logon.

Only works when invoked from the PyInstaller-frozen binary (sys.frozen == True).
From a source checkout, install manually via `pip install -e .` + scheduled task.
"""
from __future__ import annotations

import base64
import os
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

from .baked_config import strip_trailer

TASK_NAME = "ClawithBridge"


def _install_dir() -> Path:
    base = os.environ.get("LOCALAPPDATA") or str(Path.home() / "AppData" / "Local")
    return Path(base) / "Clawith" / "bin"


def _config_path() -> Path:
    return Path.home() / ".clawith-bridge.toml"


_KNOWN_ADAPTERS = ("claude_code", "openclaw", "hermes")


def _render_config(server: str, token: str, adapter: str = "claude_code") -> str:
    if adapter not in _KNOWN_ADAPTERS:
        adapter = "claude_code"
    cc = "true" if adapter == "claude_code" else "false"
    hm = "true" if adapter == "hermes" else "false"
    oc = "true" if adapter == "openclaw" else "false"
    return dedent(
        f'''\
        # Auto-generated by clawith-bridge install. Do not share this file - it contains your API key.
        server = "{server}"
        token  = "{token}"

        max_concurrent_sessions = 4

        [claude_code]
        enabled    = {cc}
        executable = "claude"

        [hermes]
        enabled  = {hm}
        base_url = "http://127.0.0.1:7890"

        [openclaw]
        enabled  = {oc}
        base_url = "http://127.0.0.1:9000"
        '''
    )


def _run_ps(script: str, check: bool = True) -> subprocess.CompletedProcess[bytes]:
    encoded = base64.b64encode(script.encode("utf-16-le")).decode()
    return subprocess.run(
        ["powershell.exe", "-NoProfile", "-NonInteractive", "-EncodedCommand", encoded],
        check=check,
        capture_output=True,
    )


def _stop_task() -> None:
    _run_ps(
        f'Stop-ScheduledTask -TaskName "{TASK_NAME}" -ErrorAction SilentlyContinue',
        check=False,
    )


def _register_task(exe_path: Path, home_dir: Path) -> None:
    script = dedent(
        f'''
        $ErrorActionPreference = "Stop"
        $Action    = New-ScheduledTaskAction -Execute "{exe_path}" -WorkingDirectory "{home_dir}"
        $Trigger   = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
        $Settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -Hidden
        $Principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
        Register-ScheduledTask -TaskName "{TASK_NAME}" -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Force | Out-Null
        Start-ScheduledTask -TaskName "{TASK_NAME}"
        '''
    )
    result = _run_ps(script, check=False)
    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", errors="replace").strip()
        stdout = result.stdout.decode("utf-8", errors="replace").strip()
        raise RuntimeError(
            f"Register-ScheduledTask failed (exit={result.returncode}).\n"
            f"stdout: {stdout}\nstderr: {stderr}"
        )


def install(*, server: str, token: str, name: str = "", adapter: str = "claude_code") -> int:
    if sys.platform != "win32":
        print("ERROR: `install` only works on Windows.", file=sys.stderr)
        print("On macOS/Linux, run the bridge directly or use launchd/systemd.", file=sys.stderr)
        return 2

    if not getattr(sys, "frozen", False):
        print("ERROR: `install` must be run from the packaged .exe, not a source checkout.", file=sys.stderr)
        print("For dev, use `pip install -e .` and register a scheduled task manually.", file=sys.stderr)
        return 2

    install_dir = _install_dir()
    exe_dest = install_dir / "clawith-bridge.exe"
    cfg_path = _config_path()
    home_dir = Path.home()
    src_exe = Path(sys.executable).resolve()

    label = f" for agent '{name}'" if name else ""
    print(f"[clawith-bridge] Installing bridge{label}...")

    # Copy the running .exe to a stable location. If we're re-running from
    # within the installed copy, skip. Otherwise stop the task so we can
    # overwrite a file the scheduler might be holding open.
    install_dir.mkdir(parents=True, exist_ok=True)
    already_at_dest = exe_dest.exists() and src_exe == exe_dest.resolve()
    if already_at_dest:
        print(f"  - already running from {exe_dest}, skipping copy")
    else:
        if exe_dest.exists():
            _stop_task()
        print(f"  - copying exe to {exe_dest}")
        try:
            shutil.copy2(src_exe, exe_dest)
        except PermissionError as e:
            print(f"\nERROR: cannot overwrite {exe_dest}: {e}", file=sys.stderr)
            print("The bridge may still be running. Stop it and retry:", file=sys.stderr)
            print(f'  powershell -Command "Stop-ScheduledTask -TaskName {TASK_NAME}"', file=sys.stderr)
            return 3

        # Strip the baked-config trailer from the installed copy so the scheduled
        # task running it never re-triggers this install flow. The original
        # download keeps its trailer and can be re-run if the user wants to
        # reinstall.
        if strip_trailer(exe_dest):
            print("  - stripped setup trailer from installed copy")

    print(f"  - writing config to {cfg_path} (adapter={adapter})")
    cfg_path.write_text(_render_config(server, token, adapter), encoding="utf-8")

    print(f"  - registering scheduled task '{TASK_NAME}' (starts at user logon)")
    try:
        _register_task(exe_dest, home_dir)
    except RuntimeError as e:
        print(f"\nERROR: {e}", file=sys.stderr)
        return 4

    print()
    print("[clawith-bridge] Done. The bridge is now running in the background.")
    print(f"  Config:    {cfg_path}")
    print(f"  Exe:       {exe_dest}")
    print(f"  Task:      {TASK_NAME}")
    print()
    print("  Check status:")
    print(f'    powershell -Command "Get-ScheduledTask -TaskName {TASK_NAME}"')
    print("  Uninstall:")
    print(f'    powershell -Command "Unregister-ScheduledTask -TaskName {TASK_NAME} -Confirm:$false"')
    print()
    print("  If Clawith still shows 'Bridge not connected', make sure the 'claude' CLI is logged in:")
    print("    npm install -g @anthropic-ai/claude-code")
    print("    claude login")
    return 0
